name: Deploy Test

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl "${{ secrets.COOLIFY_WEBHOOK_ }}"